from enum import Enum

class TriageStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    CORRECTED = "CORRECTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class TriageVerdict(str, Enum):
    AUTO_APPROVED = "AUTO_APPROVED"
    REQUIRES_TRIAGE = "REQUIRES_TRIAGE"
    MANUALLY_APPROVED = "MANUALLY_APPROVED"
    MANUALLY_REJECTED = "MANUALLY_REJECTED"
