"""Add activity_type to triage_cases

Revision ID: 113df8e0f0ba
Revises: 7a4613f1f626
Create Date: 2026-06-28 17:20:31.727796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113df8e0f0ba'
down_revision: Union[str, Sequence[str], None] = '7a4613f1f626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_cases', sa.Column('activity_type', sa.String(length=50), server_default='UNKNOWN', nullable=False))
    op.drop_column('triage_cases', 'confidence_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_cases', sa.Column('confidence_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('triage_cases', 'activity_type')
    # ### end Alembic commands ###
