"""Update TriageCaseModel with JSONB fields

Revision ID: 1827e341ff49
Revises: 68137387b6cf
Create Date: 2026-06-29 14:30:32.321450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1827e341ff49'
down_revision: Union[str, Sequence[str], None] = '68137387b6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_batches', sa.Column('description', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_batches', 'description')
    # ### end Alembic commands ###
