"""Add Person inheritance

Revision ID: 2902c6570c1d
Revises: aa3dcd4d01bf
Create Date: 2026-06-29 19:45:38.805733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2902c6570c1d'
down_revision: Union[str, Sequence[str], None] = 'aa3dcd4d01bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_dni'), 'persons', ['dni'], unique=True)
    op.create_table('beneficiaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adults',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiary_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('knows_how_to_read', sa.Boolean(), nullable=False),
    sa.Column('knows_how_to_write', sa.Boolean(), nullable=False),
    sa.Column('has_repeated_grade', sa.Boolean(), nullable=False),
    sa.Column('has_learning_difficulties', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id')
    )
    op.create_table('historical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beneficiary_id', sa.UUID(), nullable=False),
    sa.Column('has_been_hospitalized', sa.Boolean(), nullable=False),
    sa.Column('hospitalization_reason', sa.String(length=500), nullable=True),
    sa.Column('has_been_operated', sa.Boolean(), nullable=False),
    sa.Column('operation_reason', sa.String(length=500), nullable=True),
    sa.Column('vaccines', sa.JSON(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('diseases', sa.JSON(), nullable=False),
    sa.Column('insurance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.drop_table('historical_documents')
    op.drop_table('education_records')
    op.drop_table('beneficiary_enrollments')
    op.drop_table('adults')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_persons_dni'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
