"""Add batch_id to historical documents

Revision ID: 37bfc05750a3
Revises: 2902c6570c1d
Create Date: 2026-06-29 20:42:04.635185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bfc05750a3'
down_revision: Union[str, Sequence[str], None] = '2902c6570c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_documents', sa.Column('batch_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_documents', 'batch_id')
    # ### end Alembic commands ###
