"""add address, sacraments and permissions

Revision ID: 38c5010d0e4f
Revises: 69904a3010cd
Create Date: 2026-06-30 22:32:07.112390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c5010d0e4f'
down_revision: Union[str, Sequence[str], None] = '69904a3010cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('baptized', sa.Boolean(), nullable=True))
    op.add_column('beneficiaries', sa.Column('first_communion', sa.Boolean(), nullable=True))
    op.add_column('beneficiaries', sa.Column('haircut_permission', sa.Boolean(), nullable=True))
    op.add_column('beneficiaries', sa.Column('medical_exams_permission', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'address')
    op.drop_column('beneficiaries', 'medical_exams_permission')
    op.drop_column('beneficiaries', 'haircut_permission')
    op.drop_column('beneficiaries', 'first_communion')
    op.drop_column('beneficiaries', 'baptized')
    # ### end Alembic commands ###
