"""refactor_triage_case_dossier_data

Revision ID: 3cbb043a9dc0
Revises: c46b79e31445
Create Date: 2026-06-28 18:21:35.777381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cbb043a9dc0'
down_revision: Union[str, Sequence[str], None] = 'c46b79e31445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_cases', sa.Column('dossier_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('triage_cases', 'corrected_data')
    op.drop_column('triage_cases', 'documents_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_cases', sa.Column('documents_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('triage_cases', sa.Column('corrected_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('triage_cases', 'dossier_data')
    # ### end Alembic commands ###
