"""Update TriageCaseModel with JSONB fields

Revision ID: 594a3c071341
Revises: dc2c95bedcb2
Create Date: 2026-06-30 00:12:36.276733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594a3c071341'
down_revision: Union[str, Sequence[str], None] = 'dc2c95bedcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
