"""Update TriageCaseModel with JSONB fields

Revision ID: 68137387b6cf
Revises: 3cbb043a9dc0
Create Date: 2026-06-28 18:31:13.938303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68137387b6cf'
down_revision: Union[str, Sequence[str], None] = '3cbb043a9dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
