"""Update TriageCaseModel with JSONB fields

Revision ID: 7a4613f1f626
Revises: e21bd369ae13
Create Date: 2026-06-26 23:07:11.566522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a4613f1f626'
down_revision: Union[str, Sequence[str], None] = 'e21bd369ae13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('dni_reference', sa.String(length=20), nullable=False),
    sa.Column('documents_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('corrected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['extraction_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triage_case_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triage_case_id'], ['triage_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_audit_log')
    op.drop_table('triage_cases')
    # ### end Alembic commands ###
