"""Update TriageCaseModel with JSONB fields

Revision ID: aa3dcd4d01bf
Revises: 1827e341ff49
Create Date: 2026-06-29 14:38:06.171501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3dcd4d01bf'
down_revision: Union[str, Sequence[str], None] = '1827e341ff49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
