"""Update TriageCaseModel with JSONB fields

Revision ID: b32dfcfecbca
Revises: b4cea0d9df3d
Create Date: 2026-06-30 00:23:59.312204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32dfcfecbca'
down_revision: Union[str, Sequence[str], None] = 'b4cea0d9df3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
