"""rename file_url to file_id in historical_documents

Revision ID: b4cea0d9df3d
Revises: 594a3c071341
Create Date: 2026-06-30 00:20:03.456241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cea0d9df3d'
down_revision: Union[str, Sequence[str], None] = '594a3c071341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historical_documents', 'file_url', new_column_name='file_id', type_=sa.String(length=500))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historical_documents', 'file_id', new_column_name='file_url', type_=sa.String(length=1000))
    # ### end Alembic commands ###
