"""add is_emergency_contact

Revision ID: bbac9862d10c
Revises: 38c5010d0e4f
Create Date: 2026-07-01 12:09:03.849949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbac9862d10c'
down_revision: Union[str, Sequence[str], None] = '38c5010d0e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adults', sa.Column('is_emergency_contact', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adults', 'is_emergency_contact')
    # ### end Alembic commands ###
