"""initial_schema

Revision ID: cf4c2afb9076
Revises: 4db4698c4025
Create Date: 2026-06-18 01:31:11.980149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4c2afb9076'
down_revision: Union[str, Sequence[str], None] = '4db4698c4025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_items', sa.Column('code', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_items', 'code')
    # ### end Alembic commands ###
