from enum import Enum

class TriageStatus(str, Enum):
    INCOMPLETE = "INCOMPLETE"
    PENDING_REVIEW = "PENDING_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    CORRECTED = "CORRECTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class TriageVerdict(str, Enum):
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    DOCUMENT_ERROR = "DOCUMENT_ERROR"
    DATA_DISCREPANCY = "DATA_DISCREPANCY"
    AUTO_APPROVED = "AUTO_APPROVED"
    REQUIRES_TRIAGE = "REQUIRES_TRIAGE"
    MANUALLY_APPROVED = "MANUALLY_APPROVED"
    MANUALLY_REJECTED = "MANUALLY_REJECTED"

class BatchVerificationStatus(str, Enum):
    COMPLETED = "COMPLETED"
    PENDING = "PENDING"
    NOT_FOUND = "NOT_FOUND"
